function [medidasR, classes] = medidas(ver)
%Set preferences with setdbprefs.
setdbprefs('DataReturnFormat', 'numeric');
setdbprefs('NullNumberRead', 'NaN');
setdbprefs('NullStringRead', 'null');

%Make connection to database.  Note that the password has been omitted.
%Using JDBC driver.
conn = database('dodecaf', 'root', '746136', 'Vendor', 'MYSQL', 'Server', 'localhost', 'PortNumber', 3306);

switch ver
    case 'old'
        %Read data from database.
        curs = exec(conn, ['SELECT descritivos.id'...
            ' ,	descritivos.ec'...
            ' ,	descritivos.mpp'...
            ' ,	descritivos.dca'...
            ' ,	gerais.intrv_maiorN'...
            ' ,	gerais.diff_intrv'...
            ' ,	gerais.diffFL'...
            ' ,	estatisticos.frq_moda'...
            ' ,	estatisticos.mais_moda'...
            ' ,	estatisticos.moda'...
            ' ,	estatisticos.assmtr'...
            ' ,	estatisticos.m_ponderada'...
            ' ,	estatisticos.desv_p_ponderado'...
            ' FROM 	 (  (  ( `dodecaf`.descritivos '...
            ' INNER JOIN `dodecaf`.gerais '...
            ' ON 	descritivos.num = gerais.num )'...
            ' INNER JOIN `dodecaf`.estatisticos '...
            ' ON 	descritivos.num = estatisticos.num )'...
            ' INNER JOIN `dodecaf`.everything '...
            ' ON 	descritivos.num = everything.num )'...
            ' WHERE 	everything.compositor LIKE ''Arnold%'''...
            ' OR 	everything.compositor LIKE ''Igor%''']);
    case 'new'
        %Read data from database.
        curs = exec(conn, ['SELECT descritivos.mpp'...
            ' , estatisticos.mais_moda'...
            ' , estatisticos.m_artmN'...
            ' , estatisticos.modaN'...
            ' , estatisticos.dsv_pN'...
            ' , gerais.intrv_maiorN'...
            ' FROM 	 (  (  ( `dodecaf`.descritivos '...
            ' INNER JOIN `dodecaf`.gerais '...
            ' ON 	descritivos.num = gerais.num )'...
            ' INNER JOIN `dodecaf`.estatisticos '...
            ' ON 	descritivos.num = estatisticos.num )'...
            ' INNER JOIN `dodecaf`.everything '...
            ' ON 	descritivos.num = everything.num )'...
            ' WHERE 	everything.compositor LIKE ''Arnold%'''...
            ' OR 	everything.compositor LIKE ''Igor%''']);
    otherwise
            'erro';
end
       

curs = fetch(curs);
close(curs);

%Assign data to output variable
medidasR = curs.Data;

%Close database connection.
close(conn);

%Clear variables
clear curs conn

%Vetor de classes
tamanhoClasses = [19 19]; 
numClasses = size(tamanhoClasses,2);
classes = [];
for i=1:numClasses
    classesi = zeros(tamanhoClasses(i),1) + i-1;
    classes = [classes; classesi];
end

end